name: SCs Automation
author: Artur Sharapov
description: Generate and update scs files

inputs:
  github_token:
    description: A GitHub token.
    required: false
    default: ${{ github.token }}
  branch:
    description: A branch name to run action from.
    required: false
  ignore_empty:
    description: Ignore empty files [never|always].
    required: false
    default: never

runs:
  using: node16
  main: dist/index.js
