name: SCs Automation
author: Artur Sharapov
description: Generate and update scs files

inputs:
  github_token:
    description: A GitHub token.
    required: false
    default: ${{ github.token }}
  branch:
    description: A branch name to run action from.
    required: false

runs:
  using: node16
  main: dist/index.js
