name: Tests

# rebuild any PRs and main branch changes
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  # make sure build/ci work properly
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - run: npm run test
